# gcloud app deploy --project movie-db-api --version 1 --quiet
runtime: go112

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "datastore.json"

handlers:
- url: /
  static_files: index.htm
  upload: index.htm
  secure: always

- url: /find
  script: auto
  secure: always

- url: /title/tt\d+
  script: auto
  secure: always

- url: /clean
  script: auto
  secure: always
