# gcloud app deploy --project movie-db-api --version 1 --quiet
runtime: go113

handlers:
- url: /
  static_files: index.htm
  upload: index.htm
  secure: always

- url: /.*
  script: auto
  secure: always
