# goapp get -u github.com/StalkR/imdb
# HOME=. goapp deploy
application: movie-db-api
version: go
runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.htm
  upload: index.htm
  secure: always

- url: /find
  script: _go_app
  secure: always

- url: /title/tt\d+
  script: _go_app
  secure: always

- url: /cache/clean
  script: _go_app
  secure: always
  login: admin

skip_files:
- ^(.*/)?\..*
